### ISSUE TITLE
suggestion: add screenshot(s) to readme.md

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#4]
As an eye-catcher :)

**Comment by cyborgar** [comment]
Not many that could notice this before since the repository was private.

I've added a couple of screens just to have something and made the repository public. I don't really expect a huge amount of traffic :-)

If you want to link this for people to borrow code feel free to do so. It's been a fun test project for me and if anyone else want to copy code for their own Prog8 projects that is certainly fine with me.

**Comment by irmen** [comment]
oh I didn't realize it was private earlier :heart:
