### ISSUE TITLE
control issue on c64

### ISSUE THREAD

**Issue by irmen** [cyborgar/Petaxian#9]
I happened to see a couple of updates were made in Petaxian! Great!
Unfortunately it now seems something happened to the keyboard controls on the C64: I can hardy move my ship around anymore with the cursor keys.  
Using the (emulated) joystick seems to work a lot better.

**Comment by cyborgar** [comment]
Yes, I'm aware of the problem and don't have a clear fix for that. Note that it's the same for CX16.

I changed the controls so that ship only moves when actively pressing left/right etc. instead of keeping movement until changed. This work very well (and more "normal") for joystick but not for keyboard. Basically because keyboard normally return press/release events instead of contious signals.

I'm considering if I it's wort trying to figure out a way to handle keyboard better or just make it a joystick controlled game. That is easy enough for Vice but may require using a NES/SNES contoller with the CX16 emulator.

BTW, I changed this because I was asked if they could use the game as a demo for the ZZap! 64 magazine (https://fusionretrobooks.com/collections/zzap-64-magazine/products/zzap-64-micro-action-issue-6?variant=39628448268382). I'm not even sure it's included since I have not gotten the magazine myself yet (it's underway).

This also is why I was late pushing the updates. They requested a couple of weeks wait before I published anything to have a short "exclusive version" window with the magazine.

**Comment by irmen** [comment]
Hey, that's awesome! Hope they include it! It's a very nicely done game after all (regardless of the language it is made in)

**Comment by cyborgar** [comment]
I have redone the keyboard controls for C64 now. I've written a asmsub that does raw keyboard reading to get smooth controls.

I also switched code to use LEFT SHIFT (fire), K (move left) and L (move right). I'm assuming these are "stable" for C64, i.e not prone to be placed elsewhere for C64's with different located keyboards.

I currently have no idea how to do something similar for the CX16 so it's either joystick control or switching back to the "glide controls" there.

**Comment by irmen** [comment]
Did you get that ZZAP64 magazine in the end?

**Comment by cyborgar** [comment]
I got the magazine, but there where actually no demos there (I was under the impression there where supposed to be like 5 games/demos). It might have been in some digital distribution or perhaps it was dropped.

BTW, you wouldn't know how to read "raw" (or more low level) keyboard input for the CX16? As I said above I have decent keyboard controls for the C64 but it's still suck for the CX16. I've tried to search for this but haven't really found anything helpful so far.

**Comment by irmen** [comment]
Sorry, no. I do know that cc64 has some library routine (kbhit?)  that peeks into a non-public kernel variable to read keypresses, but that's not safe. And  I don't know if it is suitable for real time controlling the space ship.
Maybe there is someone on the forum or the discord with a solution.

Personally I'm fine with just using the joystick for this on X16.
I once started a game myself and had a similar issue, I just dropped keyboard control completely in favor of joystick control. But yeah not everyone will have a joystick/joypad :(

**Comment by cyborgar** [comment]
I've been focusing on the C64 lately anyway partly because the CX16 project is going a bit slowly at the moment. I have started another small game project (in Prog8) but that is is going to be C64 only (at least for now).

It's another fairly simple game where the basic idea is borrowed from a classic (extremely inspired by Llamasoft's Gridrunner). It's been going a bit slowly and does not really have a full game loop yet.

In any case I think we can consider this issue closed.

**Comment by irmen** [comment]
@cyborgar  look https://github.com/commanderx16/x16-rom/commit/4612fc6331498eccfe5837400ae60f508a6d28f9

**Comment by cyborgar** [comment]
Thanks, that is interesting. May very well make it possible to get keyboard controls on CX16. 

However, I'm probably going to wait for the eventual release of v39 of the emulator before checking it out further.

**Comment by irmen** [comment]
Sounds good! I wonder when we can expect an official r39 release. I plan on releasing an updated new Prog8 version as well to go along with it.  Good luck with the new game 🚀
